In [1]:
import pandas as pd
import sqlite3

In [2]:
# conectamos con la base de datos my_database.db
connection = sqlite3.connect("my_database.db")

# obtenemos un cursor que utilizamos para las queries
crsr = connection.cursor()

In [4]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    crsr.execute(query)

    # Almacena los datos de la query 
    ans = crsr.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in crsr.description]

    return pd.DataFrame(ans,columns=names)

In [5]:
res = crsr.execute("SELECT name FROM sqlite_master WHERE type='table'")
for name in res:
    print(name[0])

reparto
cervezas
bares
empleados

In [6]:
# crea las tablas
query = '''
CREATE TABLE IF NOT EXISTS cervezas (
     CodC VARCHAR(2),
     Envase VARCHAR(32),
     Capacidad FLOAT(2),
     Stock INT(5),
     PRIMARY KEY (CodC)
)
'''

In [7]:
query = '''

'''

crsr.execute(query)

In [ ]:
query = '''

'''

crsr.execute(query)

In [ ]:
query = '''

'''

crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
# CRUD Create Register(insert) Update Delete
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [15]:
query = '''

'''
crsr.execute(query)

NameError: name 'crsr' is not defined

In [13]:
query = '''

'''
sql_query(query)

NameError: name 'sql_query' is not defined

In [17]:
# 1 Obtener el nombre de los empleados que hayan repartido al bar Stop durante la semana 
# del 17 al 23 de octubre de 2005.

query = '''
SELECT DISTINCT e.nombre
FROM empleados AS e
INNER JOIN reparto AS r On e.CodE = r.CodE
INNER JOIN bares AS b ON r.CodB = b.CodB
WHERE b.Nombre = 'Stop'
  And r.Fecha BETWEEN '2005-10-17' AND '2005-10-23';
'''

sql_query(query)

         Nombre
0  Carlos Lopez

In [19]:
# 2 Obtener el Cif y nombre de los bares a los que se ha repartido cerveza de tipo Botella y
# capacidad inferior a 1 litro, ordenados por localidad

query = '''
SELECT b.Cif, b.nombre
FROM bares AS b
INNER JOIN reparto AS r On b.CodB = r.CodB
INNER JOIN cervezas AS c ON r.CodC = c.CodC
WHERE c.Envase = 'Botella'
  AND c.Capacidad < 1
ORDER BY b.Localidad

'''

sql_query(query)

         Cif      Nombre
0  33333333Z  Otra Ronda
1  33333333Z  Otra Ronda
2  11111111X        Stop
3  11111111X        Stop

In [20]:
# 3. Obtener los repartos (nombre del bar, envase y capacidad de la bebida, fecha y cantidad)

query = '''
SELECT b.Nombre, c.Envase, c.Capacidad, r.Fecha, r.Cantidad
FROM bares AS b
INNER JOIN reparto AS r ON b.CodB = r.CodB
INNER JOIN cervezas AS c ON r.CodC = c.CodC;
'''

sql_query(query)

        Nombre   Envase  Capacidad       Fecha  Cantidad
0         Stop  Botella       0.20  2005-10-21       240
1         Stop  Botella       0.33  2005-10-21        48
2    Las Vegas     Lata       0.33  2005-10-22        60
3   Otra Ronda   Barril      60.00  2005-10-22         4
4    Las Vegas     Lata       0.33  2005-10-22        48
5    Las Vegas   Barril      60.00  2005-10-23         2
6   Otra Ronda  Botella       0.20  2005-10-23       480
7   Otra Ronda  Botella       0.33  2005-10-24        72
8  Club Social     Lata       0.33  2005-10-24        48
9  Club Social  Botella       1.00  2005-10-25        20

In [21]:
# 4. Obtener los bares a los que se les ha repartido envases de tipo botella y capacidad 0.2 o
# 0.33

query = '''
SELECT DISTINCT b.Nombre
FROM bares AS b
INNER JOIN reparto AS r ON b.CodB = r.CodB
INNER JOIN cervezas AS c ON r.CodC = r.CodC
WHERE c.Envase = 'Botella'
  AND c.Capacidad IN (0.2, 0.33);
'''
sql_query(query)

        Nombre
0         Stop
1    Las Vegas
2   Otra Ronda
3  Club Social

In [22]:
# 5. Nombre de los empleados que han repartido a los bares "Stop" y "Las Vegas" cervezas con
# envase botella.

query = '''
SELECT DISTINCT e.Nombre
FROM empleados AS e
INNER JOIN reparto AS r ON e.CodE = r.CodE
INNER JOIN bares AS b ON r.CodB = r.CodB
INNER JOIN cervezas AS c ON r.CodC = r.CodC
WHERE b.Nombre IN ('Stop', 'Las Vegas')
  AND c.Envase = 'Botella';
'''
sql_query(query)

         Nombre
0  Carlos Lopez
1    Rosa Perez
2  Luisa Garcia

In [27]:
# 6. Obtener el nombre y número de viajes que ha realizado cada empleado fuera de Villa
# Botijo.

query = '''
SELECT e.Nombre, COUNT(r.CodE) AS Numero_Viajes
FROM empleados AS e
INNER JOIN reparto AS r ON e.CodE = r.CodE
INNER JOIN bares AS b ON r.CodB = b.CodB
WHERE b.Localidad != 'Villa Botijo'
GROUP BY e.CodE, e.Nombre;
'''

sql_query(query)

         Nombre  Numero_Viajes
0  Carlos Lopez              1
1    Rosa Perez              2
2  Luisa Garcia              2

In [ ]:
query = '''

'''
sql_query(query)

       Nombre   Localidad  litros
0  Otra Ronda  La Esponja  359.76

In [28]:
# 7. Obtener el nombre y localidad del bar que más litros de cerveza ha comprado.

query = '''
SELECT b.Nombre, b.Localidad
FROM bares AS b
INNER JOIN reparto AS r ON b.CodB = r.CodB
INNER JOIN cervezas AS c ON r.CodC = c.CodC
GROUP BY b.CodB, b.Nombre, b.Localidad
ORDER BY SUM(r.Cantidad * c.Capacidad) DESC
LIMIT 1;
'''
sql_query(query)

       Nombre   Localidad
0  Otra Ronda  La Esponja

In [29]:
# 8. Obtener los bares que han adquirido todos los tipos de cerveza con envase de botella y
# capacidad menor que 1 litro.

query = '''
SELECT b.Nombre
FROM bares AS b
INNER JOIN reparto AS r ON b.CodB = r.CodB
INNER JOIN cervezas AS c ON r.CodC = c.CodC
WHERE c.Envase = 'Botella' AND c.Capacidad < 1
GROUP BY b.CodB, b.Nombre
HAVING COUNT(DISTINCT c.CodC) = (
    SELECT COUNT(CodC) 
    FROM cervezas 
    WHERE Envase = 'Botella' AND Capacidad < 1
);
'''
sql_query(query)

       Nombre
0        Stop
1  Otra Ronda

In [ ]:
#9. Subir un 5% el sueldo del empleado que más días haya trabajado.

query = '''
UPDATE empleados
SET Sueldo = Sueldo * 1.05
WHERE CodE = (
    SELECT CodE
    FROM reparto
    GROUP BY CodE
    ORDER BY COUNT(DISTINCT Fecha) DESC
    LIMIT 1
);
'''
sql_query(query)

   Dias_trabajados CodE        Nombre
0                3    2    Rosa Perez
1                2    3  Luisa Garcia
2                2    1  Carlos Lopez

In [ ]:
query = '''

'''
sql_query(query)

   t.Sueldo * 1.05
0         115500.0

In [ ]:
query = '''
   
'''
sql_query(query)

  CodE
0    2

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
sql_query(query)

  CodE      Nombre  Sueldo
0    2  Rosa Perez  115500